"""Update address columns to be nullable

Revision ID: f5caff8a87d3
Revises: 4ba35c6162d7
Create Date: 2024-11-03 16:04:45.782553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5caff8a87d3'
down_revision = '4ba35c6162d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('county_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('county', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('county_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('country_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('country_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('county_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('country_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('county_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.alter_column('country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('county_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('county', schema=None) as batch_op:
        batch_op.alter_column('state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.alter_column('county_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
